package com.smartshift.enums;

public enum NotificationType {
    SCHEDULE_PUBLISHED,
    TIME_OFF_REQUEST_CREATED,
    TIME_OFF_REQUEST_APPROVED,
    TIME_OFF_REQUEST_REJECTED,
    OPEN_SHIFT_CLAIM_CREATED,
    OPEN_SHIFT_CLAIM_APPROVED,
    OPEN_SHIFT_CLAIM_REJECTED
}
