package com.smartshift.enums;

public enum NotificationType {
    SCHEDULE_PUBLISHED,
    TIME_OFF_REQUEST_CREATED,
    TIME_OFF_REQUEST_APPROVED,
    TIME_OFF_REQUEST_REJECTED,
    OPEN_SHIFT_CLAIM_CREATED,
    OPEN_SHIFT_CLAIM_APPROVED,
    OPEN_SHIFT_CLAIM_REJECTED,
    SHIFT_SWAP_REQUEST_CREATED,
    SHIFT_SWAP_REQUEST_ACCEPTED,
    SHIFT_SWAP_REQUEST_DECLINED,
    SHIFT_SWAP_REQUEST_APPROVED,
    SHIFT_SWAP_REQUEST_REJECTED,
    SHIFT_SWAP_REQUEST_CANCELLED,
    PAYROLL_CONFIRMED
}
